### ISSUE TITLE
Support JUnit 5.1

### ISSUE THREAD

**Issue by Timunas** [maichler/sbt-jupiter-interface#22]
It seems that `sbt-jupiter-interface`isn't working with the new version of JUnit 5.

Please consider supporting the new version in order to be able to use the most recent JUnit 5 features.

**Comment by maichler** [comment]
@Timunas Thank you. I've released 0.7.0 today which is based on JUnit 5.1.0.

**Comment by Timunas** [comment]
Awesome!
