### ISSUE TITLE
Plugin does not run JUnit 4 tests

### ISSUE THREAD

**Issue by ennru** [maichler/sbt-jupiter-interface#25]
Tests annotated with JUnit 4's `@org.junit.Test` are not discovered nor run by this plugin and it doesn't compose with the `"com.novocode" % "junit-interface"` plugin to do that either.

**Comment by maichler** [comment]
Hi ennru,

would it be possible to provide a simple project/test case which shows the issue ?

Thank you !

**Comment by ennru** [comment]
Sure. I'll give it a try.

**Comment by ennru** [comment]
I looked at the scripted tests and see that they run the JUnit 4 test as expected.
But in my [tiny test project](https://github.com/ennru/sbt-jupiter-junit4) they don't.
I played around with sbt versions and what I could think of, but the JUnit 4 test (which throws an exception) is not run during `test`.

**Comment by maichler** [comment]
Thanks ennru !` junit-interface` can't find your tests because all annotated methods are package private (which is only supported in JUnit 5). 

`junit-interface` searches for ***public*** classes annotated with ```@RunWith``` and/or ***public*** methods annotated with ```@org.junit.Test```.

**Comment by ennru** [comment]
Thank you. I was staring at this and didn't see it.
Too much Scala makes it hard to code Java...

**Comment by maichler** [comment]
No problem!

> Too much Scala makes it hard to code Java...

For me it's the other way round ;)
