### ISSUE TITLE
Wrong JUnit Vintage version

### ISSUE THREAD

**Issue by ennru** [maichler/sbt-jupiter-interface#30]
The JUnit vintage version should be 4.12 instead.

https://github.com/maichler/sbt-jupiter-interface/blob/7b146cccb9af17b24c4946f81fbd65d68f5f545f/build.sbt#L23

**Comment by maichler** [comment]
Hi ennu,

I double checked dependencies for JUnit Vintage versions 4.12.3 and 5.1.0. 

Both depend on JUnit 4.12 but require a different version of JUnit Platform (1.0.3 vs 1.1.0).  Since JUnit Jupiter 5.1.0  depends on JUnit Platform in version 1.1.0 I believe JUnit Vintage 5.1.0 is correct !?

**Comment by ennru** [comment]
I expected `junitVintage` to talk about the vintage version of JUnit that is used by Jupiter so that I would let my JUnit 4 and 5 dependencies depend on the versions used by `sbt-jupiter-interface`:
```
      "junit" % "junit" % JupiterKeys.junitVintageVersion.value % Test,
```

But you wanted to state the version of `junit-vintage-engine`? Would that ever be different than `jupiterVersion`?

**Comment by maichler** [comment]
> But you wanted to state the version of junit-vintage-engine ?

Yes. There's no property for the vintage version of JUnit since I figured that 4.12 would be the last vintage version. 

> Would that ever be different than jupiterVersion?

I'd guess no but it was different before (5.0.x vs 4.12.x).
