### ISSUE TITLE
Incompatibility with JUnit 5.6+

### ISSUE THREAD

**Issue by slandelle** [maichler/sbt-jupiter-interface#44]
Hi there,

It looks like the plugin (tested with latest 0.8.3) only works with JUnit up to 5.5.2 and starts crashing starting with 5.6.0 (current version is 5.7.0):

```
java.lang.RuntimeException: Test identifier without source: TestIdentifier [uniqueId = '[engine:junit-jupiter]', parentId = null, displayName = 'JUnit Jupiter', legacyReportingName = 'JUnit Jupiter', source = null, tags = [], type = CONTAINER]
	at net.aichler.jupiter.internal.Configuration.lambda$extractClassName$1(Configuration.java:177)
```

Am I missing something?

Regards

**Comment by maichler** [comment]
Hej,

> Am I missing something?

no, this is an internal exception which unfortunately suppresses the original cause. Could you please try version 0.8.4 which I just released ? With this version you should see the real error.

Thanks!

**Comment by slandelle** [comment]
Cool, thanks!

So indeed, I now see the actual exception:

```
java.lang.ClassNotFoundException: org.junit.jupiter.api.extension.ScriptEvaluationException
[error]     at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[error]     at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
[error]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
[error]     at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
```

Indeed, this class was removed in JUnit 5.6.0. It doesn't seem to be used anywhere in the code of this plugin, so I suspect the issue is unaligned JUnit modules versions. I only import `junit-jupiter-api:5.7.0`.

**Comment by maichler** [comment]
It seems so indeed. 

Have a look at the ivy report of the test dependencies in your project (target/scala-2.x/resolution-cache/reports/), specifically which junit module is still on 5.1.1 and add that module as explicit dependency.

For me it was junit-jupiter-engine.

**Comment by slandelle** [comment]
Indeed, that was the issue, `junit-jupiter-engine` version has to be enforced too.
Thanks  a lot!
